name = "HLConv"
uuid = "f61ebf39-2048-41b7-8c83-32a743150fdd"
authors = ["陈久宁 <chenjiuning@tongyuan.cc>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
Libdl = "1.11.0"
julia = "1.7"
